### ISSUE TITLE
PiouslyLogo hovers/clicks not registered if mouse is moving while loading window

### ISSUE THREAD

**Issue by ben9583** [harshavb/piously#15]
~~If the user hovers/clicks the piously logo very quickly as the game is loading in, future hovers and clicks aren't registered until the game is restarted.~~

Following a more in-depth look at the issue, it seems as though UIEvents aren't being registered if the mouse is moving while the window is loading in. The required fix is to reload the application in some way—either by selecting on another app to focus on and back to the dotnet app or by just restarting the game.

**Comment by ben9583** [comment]
Just some clarification on the issue: When the program starts and the mouse doesn't move until a second or two after the window loads, it works fine. Otherwise, no inputs are registered by the game and require the user to click on some other application to focus on that and then click back onto the dotnet app, which fixes the issue.

I've tried debugging the TestHoverableContainer, but when the issue is happening, the OnHover function does not run at all. This may just be a MacOS issue, so if someone on Windows could try this, that would be helpful too. In the meantime, I'm gonna delay this issue until we get more information.

**Comment by harshavb** [comment]
seems to only be an issue on mac

**Comment by ben9583** [comment]
Issue has been forwarded to osu-framework:
https://github.com/ppy/osu-framework/issues/3976

Suspending issue until a response a received.

**Comment by ben9583** [comment]
Closing untill upstream update on issue.
