### ISSUE TITLE
Create a Menu GUI

### ISSUE THREAD

**Issue by ben9583** [harshavb/piously#23]
The menu GUI will be the screen presented to the user when they click on the Piously icon after the game loads. Clicking on the icon will spawn in six trapezoids surrounding the logo as if extending the hexagon. It should have this sort of framework:

<img width="734" alt="Screen Shot 2020-11-05 at 9 41 35 AM" src="https://user-images.githubusercontent.com/16968917/98269623-2e9d4880-1f4b-11eb-8e0a-70f768dc4d81.png">

**Comment by harshavb** [comment]
Unsure whether the buttons should be part of the same screen or whether the open and closed logo should be two different screens which get pushed to a single screenstack. Assuming the latter for now.
