### ISSUE TITLE
Issues with hover logic on menu buttons

### ISSUE THREAD

**Issue by harshavb** [harshavb/piously#31]
If a user stops hovering over a menu button by rehovering over the logo, it works fine. However, if a user stops hovering over a menu button by hovering over the background, things break.

**Comment by ben9583** [comment]
Unable to reproduce locally; can you send a clip of it happening?

**Comment by harshavb** [comment]
Pull.

**Comment by ben9583** [comment]
Fixed with 93b04d4. Closing
