### ISSUE TITLE
Design a local multiplayer ui

### ISSUE THREAD

**Issue by ben9583** [harshavb/piously#36]
Before programming in the ui, we should spend some time on describing the layout and options available to users once they click the local game button on the main menu.

**Comment by johnnthough** [comment]
Hello i am a UI designer and i believe i can be of help to you

**Comment by ben9583** [comment]
We're always looking for help; if you have an idea, we'd be happy to it check out

**Comment by ben9583** [comment]
Just to get an idea of what we're thinking, I've made some preliminary wireframes of how I imagine it could look like. I'm not really good in this field, but I try my best:

What the user will see when they start click the menu button to create a local game (background coming later)
![Start](https://user-images.githubusercontent.com/16968917/100625809-3e0d7880-32e2-11eb-9794-90fbb45bdec7.png)

When the user clicks "New Game." They are given some options to configure their game (just a timer for now) and can name the players.
![New Game](https://user-images.githubusercontent.com/16968917/100625821-42d22c80-32e2-11eb-8707-5ce7092792e0.png)

When the user clicks "Load Saved Game." They are presented with a list of previously saved games with their last date played (not sorted in this, but likely will be later). The player names for the game selected will appear on the bottom left.
![Load Saved Game](https://user-images.githubusercontent.com/16968917/100625839-4665b380-32e2-11eb-9a46-e2ee8d027667.png)

**Comment by johnnthough** [comment]
I actually like this task , I would love to help , can you tell me a bit
about the game or the plans you have for this game, where will it be
available to play or download.

**Comment by johnnthough** [comment]
this is my personal email davecole006@gmail.com

**Comment by ben9583** [comment]
Piously is a turn-based, strategy board game that we're creating using `osu-framework`. More in-depth information is available on the readme at the project root. For now, we've got the opening menu and settings/config set up, so we are now going to start work on the local multiplayer game setup UI before working on the game itself. Later, we'll set up a singleplayer mode with an AI later and then an online mode with ranked as well as casual games.

For now, you can get the game by cloning the GitHub repo and building with Visual Studio. We'll be making a website in the future where it will be available as a release download once we get a playable game up and running.

**Comment by ben9583** [comment]
@johnnthough I'll send you an invite to our development discord server.

**Comment by ben9583** [comment]
Mostly done, moving on to focus on programming this in.
