### ISSUE TITLE
Tooltips are misplaced

### ISSUE THREAD

**Issue by harshavb** [harshavb/piously#44]
Currently, tooltips are completely offset from the cursor, and seem to move around quite a bit. My guess as to why this happens is that PiouslyCursor or PiouslyCursorContainer is implemented unusually, and the cursor rotation is what causes the janky movement.

**Comment by ben9583** [comment]
I think I might know what causes this; I'll work on this a bit later.

**Comment by ben9583** [comment]
Resolved with 099fa4f

**Comment by harshavb** [comment]
Tooltips are still misplaced when dragging.

**Comment by ben9583** [comment]
Actually fixed with 25665b6
