### ISSUE TITLE
Create hexagon groups

### ISSUE THREAD

**Issue by harshavb** [harshavb/piously#52]
Many elements of the game, such as the board, segments of the board, and the local game options background, require a set of hexagons which are connected to each other, with any given hexagon having 0-6 other hexagons connected. Ideally, we want to implement this with optional spacing between the hexagons. Each hexagon group should be a container, so that it's easily rotatable and scalable. The coordinates of each hexagon should be determined solely from the position, rotation, scale, and spacing of the hexagon group. Current idea is to create a coordinate grid based on those variables, and then assign hexagons to the grid as needed. It could be helpful to have a Vector2 offset as well to position the grid offset from the position of the hexagon group itself.

**Comment by harshavb** [comment]
Creating via `HexagonGroup.cs`

**Comment by harshavb** [comment]
![Capture](https://user-images.githubusercontent.com/48032800/103124064-b5190100-4643-11eb-87f5-aa8012fc29b0.PNG)
Hexagons should be laid out as such.

**Comment by harshavb** [comment]
I've realized that there are many instances where we want consistent hexagon sizes among differently sized hexagon groups. So, there should be a variable `hexagonSize` and `HexagonSize` which determine the size of the overall hexagon group based on the value of the variable. If no value is given for `HexagonSize`, then the total hexagon group will be sized base on `Size` alone, with all hexagons fitting inside.

**Comment by ben9583** [comment]
Note that regarding the coordinate system, there is another way we should consider that results in consistent basis vectors and not needing to use `if(mod(x, 2) == 1) position.y -= hexagon.height`:
![a](https://user-images.githubusercontent.com/16968917/103159192-7b4f1400-4783-11eb-8005-28df5486058c.png)

**Comment by harshavb** [comment]
Makes sense, switching to that layout instead.

**Comment by ben9583** [comment]
The actual grid:

<img width="742" alt="Screen Shot 2020-12-26 at 3 51 18 PM" src="https://user-images.githubusercontent.com/16968917/103160429-38e10380-4792-11eb-843b-f3ab2f7a1862.png">

**Comment by harshavb** [comment]
Closed by https://github.com/harshavb/piously/commit/6bbba30ed26b27410e50272e6f80a4b4b70691ed
